feat: tags

diff --git a/bic b/bic
--- a/bic
+++ b/bic
@@ -144,7 +144,6 @@ build_pages() {
 build_posts() {
   [[ ! -d "${SRC_DIR}"/posts || ! -f "${SRC_DIR}"/entry.html ]] && return
   ALL_POSTS=()
-  declare -A ALL_TAGS
   for _post in "${SRC_DIR}"/posts/*.md; do
     log "Building post: ${_post}"
     [[ "${_post}" =~ \| ]] && fatal "Filename cannot contain a pipe literal (used internally for delimitting tagged entries)"
@@ -154,24 +153,18 @@ build_posts() {
     filename="$(basename "${_post}")"
     filename_sans_id="$(echo "${filename}" | sed -E 's/^[0-9]+-//')"
     for _tag in $(mk_tags "${_post}"); do
-      tags+=("${_tag}")
-      # TODO: how to delimit?
-      if [[ -n "${ALL_TAGS["${_tag}"]:-}" ]]; then
-        ALL_TAGS["${_tag}"]+="|${_post}"
+      local slug
+      slug="$(mk_slug "${_tag}")"
+      tags+=("${slug}")
+      if [[ -n "${ALL_TAGS["${slug}"]:-}" ]]; then
+        ALL_TAGS["${slug}"]+="|${_post}"
       else
-        ALL_TAGS["${_tag}"]="${_post}"
+        ALL_TAGS["${slug}"]="${_post}"
       fi
     done
 
     (
       post=true
-      # TODO: probably remove
-      # works
-      # mapfile -t tags < <(mk_tags "${_post}")
-      # worse option: forces word splitting
-      # tags=($(mk_tags "${_post}"))
-      # hard coding for testing
-      # tags=("one" "two" "three")
       title="$(mk_title "${_post}")"
       body="$(mk_body "${_post}")"
       date="$(mk_date "${_post}")"
@@ -213,6 +206,55 @@ build_drafts() {
   unset _draft
 }
 
+build_tags() {
+  [[ ! -f "${SRC_DIR}"/tags.html || ! -f "${SRC_DIR}"/tag.html || ! -f "${SRC_DIR}"/__tag.html ]] && return
+
+  declare -A all_tags
+  for tag in "${!ALL_TAGS[@]}"; do
+    IFS='|' read -r -a posts <<< "${ALL_TAGS["${tag}"]}"
+    all_tags["${tag}"]="${#posts[@]}"
+    build_tag "${tag}"
+  done
+
+  log "Building tags.html"
+  (
+    title="All tags"
+    export title all_tags
+    mo \
+      "${SRC_DIR}"/tags.html \
+      > "${DEST_DIR}"/tags.html
+  )
+}
+
+build_tag() {
+  log "Building tags/${1}.html"
+
+  local __tag=""
+  local _posts
+  local tag="${1}"
+  IFS='|' read -r -a posts <<< "${ALL_TAGS["${tag}"]}"
+  for post in "${posts[@]}"; do
+    local filename filename_sans_id title date slug id
+    filename="$(basename "${post}")"
+    filename_sans_id="$(echo "${filename}" | sed -E 's/^[0-9]+-//')"
+    title="$(mk_title "${post}")"
+    date="$(mk_date "${post}")"
+    slug="$(mk_slug "${filename_sans_id%.md}")"
+    id="$(mk_id "${filename}" "${filename_sans_id}")"
+    __tag+="$(mo "${SRC_DIR}"/__tag.html)"
+    __tag+=$'\n'
+  done
+
+  mkdir -p "${DEST_DIR}"/tags
+  (
+    title="All posts tagged ${tag}"
+    export __tag title tag
+    mo \
+      "${SRC_DIR}"/tag.html \
+      > "${DEST_DIR}/tags/${tag}.html"
+  )
+}
+
 build_index() {
   log "Building index.html"
 
@@ -239,7 +281,7 @@ build_index() {
 }
 
 build_sitemap() {
-  [[ ! -f "${SRC_DIR}/sitemap.xml" ]] && return
+  [[ ! -f "${SRC_DIR}"/sitemap.xml ]] && return
   log "Building sitemap.xml"
 
   local slugs=()
@@ -281,7 +323,7 @@ build_robots() {
 }
 
 build_feed() {
-  [[ ! -f "${SRC_DIR}/feed.rss" || ! -f "${SRC_DIR}"/__feed.rss ]] && return
+  [[ ! -f "${SRC_DIR}"/feed.rss || ! -f "${SRC_DIR}"/__feed.rss ]] && return
   log "Building feed.rss"
 
   local __feed=""
@@ -324,11 +366,11 @@ build() {
   # File system: what's missing and do we need to bail?
   [[ -d "${SRC_DIR}"/pages && -f "${SRC_DIR}"/page.html  ]] || warn "pages/ + page.html for pages"
   [[ -d "${SRC_DIR}"/posts && -f "${SRC_DIR}"/entry.html ]] || warn "posts/ + entry.html for posts"
-  [[ -f "${SRC_DIR}"/index.html && -f "${SRC_DIR}"/__index.html ]]  || fatal "index.html (and __index.html) required"
-  [[ -f "${SRC_DIR}"/feed.rss   && -f "${SRC_DIR}"/__feed.rss ]]    || warn "feed.rss (and __feed.rss) for an RSS feed"
+  [[ -f "${SRC_DIR}"/index.html && -f "${SRC_DIR}"/__index.html                           ]] || fatal "index.html (and __index.html) required"
+  [[ -f "${SRC_DIR}"/feed.rss   && -f "${SRC_DIR}"/__feed.rss                             ]] || warn "feed.rss (and __feed.rss) for an RSS feed"
+  [[ -f "${SRC_DIR}"/tags.html  && -f "${SRC_DIR}"/tag.html && -f "${SRC_DIR}"/__tag.html ]] || warn "tags.html, tag.html (and __tag.html) for tagging entries"
   [[ -f "${SRC_DIR}"/sitemap.xml ]] || warn "sitemap.xml for a sitemap for search engines"
   [[ -f "${SRC_DIR}"/robots.txt ]]  || warn "robots.txt for web crawlers"
-  # TODO: add logic for tags?
 
   # Environment: anything not set that probably should be?
   [[ -n "${SITE_AUTHOR:-}" ]] || warn "\$SITE_AUTHOR not set"
@@ -340,11 +382,13 @@ build() {
   [[ -d "${DEST_DIR}" ]] && rm -rf "${DEST_DIR}"
   mkdir -p "${DEST_DIR}" && log "Created build directory: ${DEST_DIR}"
 
+  # Need to declare this slightly more globally otherwise can't share it across functions 🤷
+  declare -A ALL_TAGS
+
   build_pages   # side effect(s): $ALL_PAGES
   build_posts   # side effect(s): $ALL_POSTS, $ALL_TAGS
   build_drafts  # side effect(s): $ALL_DRAFTS
-  # TODO: implement
-  # build_tags    # uses $ALL_TAGS, $ALL_PAGES
+  build_tags    # uses $ALL_TAGS
   build_index   # uses $ALL_POSTS
   build_sitemap # uses $ALL_PAGES, $ALL_POSTS
   build_robots
