feat: tags (#18)
* wip: minimal tags for a post are parsed

* wip: confirm no immediate regression for no tags

* chore: update `mo`

* test: try out more tags w/ overlap

* feat: tagged entries with "|"; add test to enforce

* feat: tags

* docs: tags

* refactor: remove todo

* refactor: more DRY checking for tags

* feat: add tags to sitemap

* docs: RFC 2119 compliance

* docs: more RFC 2119

* feat: add `has_tags` for entries

* fix: do tags for drafts, just don't ALL_TAGS 'em

* docs(readme): specify Docker platform

* fix: bad copypasta

* fix: `has_tags`

* refactor: opt for checking `tags.0` vs `has_tags`

* docs(readme): use browser sync via `npx`

diff --git a/bic b/bic
--- a/bic
+++ b/bic
@@ -25,6 +25,8 @@ source "${__dir}"/lib/mo
 PANDOC_EXTS="+autolink_bare_uris+gfm_auto_identifiers+task_lists"
 PANDOC_ARGS=(-f markdown"${PANDOC_EXTS:-}" -t html5 --columns 1000 --no-highlight --email-obfuscation=none)
 
+TAG_PREFIX="tags:"
+
 # Print out usage information
 usage() {
   cat <<HEREDOC
@@ -59,6 +61,13 @@ html_escape() {
   echo "${1:-}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
 }
 
+__has_tags() {
+  local tagline
+  tagline="$(head -n 2 < "${1}" | tail -n 1)"
+  [[ "$tagline" == "$TAG_PREFIX"* ]] && return 0
+  return 1
+}
+
 mk_title() {
   local title
   title="$(head -n 1 < "${1}")"
@@ -69,7 +78,21 @@ mk_title() {
 }
 
 mk_body() {
-  pandoc "${PANDOC_ARGS[@]}" <(tail -n +2 "${1}")
+  if __has_tags "${1}"; then
+    pandoc "${PANDOC_ARGS[@]}" <(tail -n +3 "${1}")
+  else
+    pandoc "${PANDOC_ARGS[@]}" <(tail -n +2 "${1}")
+  fi
+}
+
+mk_tags() {
+  if __has_tags "${1}"; then
+    local tagline split
+    tagline="$(head -n 2 < "${1}" | tail -n 1)"
+    split="$(echo "${tagline#"$TAG_PREFIX"}" | tr -d '[:space:]')"
+    IFS=',' read -r -a tags <<< "$split"
+    echo "${tags[@]}"
+  fi
 }
 
 mk_slug() {
@@ -127,10 +150,21 @@ build_posts() {
   ALL_POSTS=()
   for _post in "${SRC_DIR}"/posts/*.md; do
     log "Building post: ${_post}"
+    [[ "${_post}" =~ \| ]] && fatal "Filename cannot contain a pipe literal (used internally for delimitting tagged entries)"
     ALL_POSTS+=("${_post}")
-    local filename filename_sans_id
+    local filename filename_sans_id tags=()
     filename="$(basename "${_post}")"
     filename_sans_id="$(echo "${filename}" | sed -E 's/^[0-9]+-//')"
+    for _tag in $(mk_tags "${_post}"); do
+      local slug
+      slug="$(mk_slug "${_tag}")"
+      tags+=("${slug}")
+      if [[ -n "${ALL_TAGS["${slug}"]:-}" ]]; then
+        ALL_TAGS["${slug}"]+="|${_post}"
+      else
+        ALL_TAGS["${slug}"]="${_post}"
+      fi
+    done
 
     (
       post=true
@@ -139,7 +173,7 @@ build_posts() {
       date="$(mk_date "${_post}")"
       slug="$(mk_slug "${filename_sans_id%.md}")"
       id="$(mk_id "${filename}" "${filename_sans_id}")"
-      export title body date slug id post
+      export title body date slug id post tags
       mo \
         "${SRC_DIR}"/entry.html \
         > "${DEST_DIR}/${slug}.html"
@@ -154,9 +188,14 @@ build_drafts() {
   for _draft in "${SRC_DIR}"/drafts/*.md; do
     log "Building draft: ${_draft}"
     ALL_DRAFTS+=("${_draft}")
-    local filename filename_sans_id
+    local filename filename_sans_id tags=()
     filename="$(basename "${_draft}")"
     filename_sans_id="$(echo "${filename}" | sed -E 's/^[0-9]+-//')"
+    for _tag in $(mk_tags "${_draft}"); do
+      local slug
+      slug="$(mk_slug "${_tag}")"
+      tags+=("${slug}")
+    done
     mkdir -p "${DEST_DIR}"/drafts
 
     (
@@ -166,13 +205,62 @@ build_drafts() {
       date="$(mk_date "${_draft}")"
       slug="$(mk_slug "${filename_sans_id%.md}")"
       id="$(mk_id "${filename}" "${filename_sans_id}")"
-      export title body date slug id draft
+      export title body date slug id draft tags
       mo \
         "${SRC_DIR}"/entry.html \
         > "${DEST_DIR}/drafts/${slug}.html"
     )
   done
   unset _draft
+}
+
+build_tags() {
+  [[ ! -f "${SRC_DIR}"/tags.html || ! -f "${SRC_DIR}"/tag.html || ! -f "${SRC_DIR}"/__tag.html ]] && return
+
+  declare -A all_tags
+  for tag in "${!ALL_TAGS[@]}"; do
+    IFS='|' read -r -a posts <<< "${ALL_TAGS["${tag}"]}"
+    all_tags["${tag}"]="${#posts[@]}"
+    build_tag "${tag}"
+  done
+
+  log "Building tags.html"
+  (
+    title="All tags"
+    export title all_tags
+    mo \
+      "${SRC_DIR}"/tags.html \
+      > "${DEST_DIR}"/tags.html
+  )
+}
+
+build_tag() {
+  log "Building tags/${1}.html"
+
+  local __tag=""
+  local _posts
+  local tag="${1}"
+  IFS='|' read -r -a posts <<< "${ALL_TAGS["${tag}"]}"
+  for post in "${posts[@]}"; do
+    local filename filename_sans_id title date slug id
+    filename="$(basename "${post}")"
+    filename_sans_id="$(echo "${filename}" | sed -E 's/^[0-9]+-//')"
+    title="$(mk_title "${post}")"
+    date="$(mk_date "${post}")"
+    slug="$(mk_slug "${filename_sans_id%.md}")"
+    id="$(mk_id "${filename}" "${filename_sans_id}")"
+    __tag+="$(mo "${SRC_DIR}"/__tag.html)"
+    __tag+=$'\n'
+  done
+
+  mkdir -p "${DEST_DIR}"/tags
+  (
+    title="All posts tagged ${tag}"
+    export __tag title tag
+    mo \
+      "${SRC_DIR}"/tag.html \
+      > "${DEST_DIR}/tags/${tag}.html"
+  )
 }
 
 build_index() {
@@ -201,7 +289,7 @@ build_index() {
 }
 
 build_sitemap() {
-  [[ ! -f "${SRC_DIR}/sitemap.xml" ]] && return
+  [[ ! -f "${SRC_DIR}"/sitemap.xml ]] && return
   log "Building sitemap.xml"
 
   local slugs=()
@@ -221,6 +309,13 @@ build_sitemap() {
     slug="$(mk_slug "${filename_sans_id%.md}")"
     slugs+=("$(html_escape "${slug}")")
   done
+
+  if [[ -f "${SRC_DIR}"/tags.html && -f "${SRC_DIR}"/tag.html && -f "${SRC_DIR}"/__tag.html ]]; then
+    slugs+=("$(html_escape "tags")")
+    for tag in "${!ALL_TAGS[@]}"; do
+      slugs+=("$(html_escape "tags/${tag}")")
+    done
+  fi
 
   (
     export slugs
@@ -243,7 +338,7 @@ build_robots() {
 }
 
 build_feed() {
-  [[ ! -f "${SRC_DIR}/feed.rss" || ! -f "${SRC_DIR}"/__feed.rss ]] && return
+  [[ ! -f "${SRC_DIR}"/feed.rss || ! -f "${SRC_DIR}"/__feed.rss ]] && return
   log "Building feed.rss"
 
   local __feed=""
@@ -286,8 +381,9 @@ build() {
   # File system: what's missing and do we need to bail?
   [[ -d "${SRC_DIR}"/pages && -f "${SRC_DIR}"/page.html  ]] || warn "pages/ + page.html for pages"
   [[ -d "${SRC_DIR}"/posts && -f "${SRC_DIR}"/entry.html ]] || warn "posts/ + entry.html for posts"
-  [[ -f "${SRC_DIR}"/index.html && -f "${SRC_DIR}"/__index.html ]]  || fatal "index.html (and __index.html) required"
-  [[ -f "${SRC_DIR}"/feed.rss   && -f "${SRC_DIR}"/__feed.rss ]]    || warn "feed.rss (and __feed.rss) for an RSS feed"
+  [[ -f "${SRC_DIR}"/index.html && -f "${SRC_DIR}"/__index.html                           ]] || fatal "index.html (and __index.html) required"
+  [[ -f "${SRC_DIR}"/feed.rss   && -f "${SRC_DIR}"/__feed.rss                             ]] || warn "feed.rss (and __feed.rss) for an RSS feed"
+  [[ -f "${SRC_DIR}"/tags.html  && -f "${SRC_DIR}"/tag.html && -f "${SRC_DIR}"/__tag.html ]] || warn "tags.html, tag.html (and __tag.html) for tagging entries"
   [[ -f "${SRC_DIR}"/sitemap.xml ]] || warn "sitemap.xml for a sitemap for search engines"
   [[ -f "${SRC_DIR}"/robots.txt ]]  || warn "robots.txt for web crawlers"
 
@@ -301,9 +397,13 @@ build() {
   [[ -d "${DEST_DIR}" ]] && rm -rf "${DEST_DIR}"
   mkdir -p "${DEST_DIR}" && log "Created build directory: ${DEST_DIR}"
 
+  # Need to declare this slightly more globally otherwise can't share it across functions 🤷
+  declare -A ALL_TAGS
+
   build_pages   # side effect(s): $ALL_PAGES
-  build_posts   # side effect(s): $ALL_POSTS
+  build_posts   # side effect(s): $ALL_POSTS, $ALL_TAGS
   build_drafts  # side effect(s): $ALL_DRAFTS
+  build_tags    # uses $ALL_TAGS
   build_index   # uses $ALL_POSTS
   build_sitemap # uses $ALL_PAGES, $ALL_POSTS
   build_robots
